### ISSUE TITLE
Rename or give a new name to this project

### ISSUE THREAD

**Issue by resouer** [oam-dev/velaux#133]
Hey @oam-dev/vela-maintainers , as KubeVela is essentially control plane mode, I saw there's some confusion raised in Gitter/Slack that they can't figure out the goal of `velacp`. We should fix that.

Note that `velacp` as the UI/DevEx layer for KubeVela is definitely valuable and priority 1 task for vela team. Though we do want to maintain this layer separately so users have freedom of choice.

Some idea:
```
veladev, velaui, veladx ...
```

**Comment by hongchaodeng** [comment]
What about `velaux`?

**Comment by resouer** [comment]
@hongchaodeng `velaux` SGTM!

**Comment by wonderflow** [comment]
velaux +1
