### ISSUE TITLE
[bug]git clone is failed

### ISSUE THREAD

**Issue by shikanon** [oam-dev/velaux#169]
When I git clone the repo , it raise the error like this:
```
$ git clone https://github.com/oam-dev/velaux.git
Cloning into 'velaux'...
remote: Enumerating objects: 4064, done.
remote: Counting objects: 100% (1458/1458), done.
remote: Compressing objects: 100% (919/919), done.
remote: Total 4064 (delta 681), reused 1096 (delta 433), pack-reused 2606
Receiving objects: 100% (4064/4064), 6.64 MiB | 1.74 MiB/s, done.
Resolving deltas: 100% (2101/2101), done.
error: invalid path '.eslintrc.js '
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
```

**Comment by ivanfoo** [comment]
Hi @shikanon,

It is working fine for me, I've just cloned the repository as I was playing with it

Can you double check?

**Comment by shikanon** [comment]
@ivanfoo I use windows system it will failed, and use linux system will well.

![image](https://user-images.githubusercontent.com/7250620/141905036-1097db96-d52b-4f8f-b4d0-7a8679d3a100.png)

![image](https://user-images.githubusercontent.com/7250620/141905191-636f2592-cf99-4474-b2ab-1a39466a1fba.png)
