### ISSUE TITLE
[BUG] Correct the info related to Terraform addon

### ISSUE THREAD

**Issue by BinaryHB0916** [oam-dev/velaux#253]
Right now, we don't have to enable terraform individually and we have no terraform listed in addons to be enabled.

Please consider to correct the infos as below in each of terraform-providers(Alibaba, AWS, Azure):

![1A87E776-9110-4706-A14F-3677B908D035](https://user-images.githubusercontent.com/57997154/145181626-1b223b28-6000-4f05-97fa-a024f2f8cce3.png)

**Comment by barnettZQG** [comment]
It should be displayed, and we should support clicking on it to query its enablement information. It should not be limited to lists. @BinaryHB0916

**Comment by wangbow** [comment]
![image](https://user-images.githubusercontent.com/21334770/147237005-883c94b8-1c48-4993-9742-3c39b3def871.png)

Jump to the Addon terraform page display by clicking on terraform.  Is this plan feasible ? @barnettZQG  @BinaryHB0916
