### ISSUE TITLE
[Feature] query the application service endpoint from Ingress.

### ISSUE THREAD

**Issue by barnettZQG** [oam-dev/velaux#256]
Currently, support queries the application service endpoint from service, which must be Load Balancer type.

We should support queries from the ingress belonging to the application.

**Comment by barnettZQG** [comment]
https://github.com/oam-dev/velaux/blob/03811ead8e290a0193359445ff6ed03c92b239aa/src/pages/ApplicationInstanceList/index.tsx#L462

**Comment by barnettZQG** [comment]
oam-dev/kubevela#3052 supported query service endpoints by velaQL.  

`service-endpoints-view{appName=%s,appNs=%s}.endpoints` 

response body like this:
```
[
 {
    endpoint: {
      protocol: string
      appProtocol: string
      host: string
      port: number
      path: string
    },
    ref: {}
 }
]
```

build endpoint string reference https://github.com/oam-dev/kubevela/blob/53d3ff69158a959ba8d0613885a897b55d4dedd7/pkg/velaql/providers/query/types/type.go#L44

**Comment by wangbow** [comment]
This issue is fixed,  Could you help me to closed it? @barnettZQG
