### ISSUE TITLE
addon velaux status is always enabling

### ISSUE THREAD

**Issue by leejanee** [oam-dev/velaux#260]
I install addon `velaux` according to the steps in the official document（kubevela.io[https://kubevela.io]）
But, addon velaux status is always enabling.

I found the problem is that the velaux pod is crashing.
![image](https://user-images.githubusercontent.com/74582607/145523402-859da285-a85b-4e60-857f-2750cd11d768.png)

And the logs of velaux pod is as follow:
```
2021/12/10 05:30:29 [emerg] 1#1: host not found in upstream "apiserver.vela-system:8000" in /etc/nginx/nginx.conf:32
nginx: [emerg] host not found in upstream "apiserver.vela-system:8000" in /etc/nginx/nginx.conf:32
```

**Comment by barnettZQG** [comment]
@leejanee  Check whether the DNS service is running properly in the cluster.

**Comment by leejanee** [comment]
> @leejanee Check whether the DNS service is running properly in the cluster.

Yes, It seems to be a problem with my cluster that the dns is not installed.  So, I will close this report.
