### ISSUE TITLE
[BUG] edit properties disable liveness readness ..etc, not work

### ISSUE THREAD

**Issue by ThinerZQ** [oam-dev/velaux#262]
when i disable liveness readness, then deploy , the app still enable liveness readness

**Comment by ThinerZQ** [comment]
![image](https://user-images.githubusercontent.com/10881023/145538006-76e3519a-2652-4863-8900-237873032036.png)
disable ,but not work
![image](https://user-images.githubusercontent.com/10881023/145538378-be666ae0-bd7a-4500-aa12-0563d44f8a1f.png)

**Comment by wangbow** [comment]
确实是个问题。当关闭switch状态框的时候，需要对form readinessProbe 的value进行移除操作，否则在应用创建的时候，readinessProbe的数据 还是会保持到Server，导致用户产生误解。

**Comment by barnettZQG** [comment]
Group 的 switch 开关含义是隐藏和展示，应该在 Group 包装的 UISchema 组件中标记禁用和启用，启用后生成表单和进行数据校验。同时编辑过程中，有配置数据即为启用。
