### ISSUE TITLE
[Feature] Show the addon detail status.

### ISSUE THREAD

**Issue by wangyikewxgm** [oam-dev/velaux#264]
Now if an addon get stuck in `enabling` phase because of some reasons,  there aren't any ways for user to know what happened.  This [pr](https://github.com/oam-dev/kubevela/pull/2910) set a field as `DetailWorkflowInfo` which contains the addon related application `detailWorkflowInfo`. And this field will always have the the reason of application hanging.
eg:
    
{
"name": "fluxcd",
"phase": "enabling",
"args": null,
"detailWorkflowInfo": "[{"id":"498cywf5sl","name":"deploy-control-plane","type":"apply-application","phase":"failed","message":"step output: step components: step 1: run step(provider=oam,do=component-apply): DispatchStandardWorkload: cannot apply manifest, name: \"webhook-receiver\" apiVersion: \"v1\" kind: \"Service\": cannot create object: services \"webhook-receiver\" is forbidden: unable to create new content in namespace flux-system because it is being terminated","reason":"Execute","firstExecuteTime":"2021-12-10T10:23:46Z","lastExecuteTime":"2021-12-10T10:23:46Z"}]"
}

**Comment by barnettZQG** [comment]
@wangyikewxgm Describe your solution directly.

**Comment by wangyikewxgm** [comment]
> @wangyikewxgm Describe your solution directly.

Updated the content.
