### ISSUE TITLE
[BUG] the target can not be shown.

### ISSUE THREAD

**Issue by barnettZQG** [oam-dev/velaux#265]
![image](https://user-images.githubusercontent.com/18493394/145747481-4573ce34-5b88-4734-8721-c3f305cdc89b.png)
Normally, it should be displayed as an alias for Target.

**Comment by wangbow** [comment]
![image](https://user-images.githubusercontent.com/21334770/146149610-1490d9af-0659-454a-bbc5-60a80fddcf9a.png)
