### ISSUE TITLE
Make link text in the description of a parameter to by a superlink

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/velaux#288]
![image](https://user-images.githubusercontent.com/2805315/146895429-449072c6-14fa-4466-acca-6d72af859854.png)

Make the link text in `Get ALICLOUD_ACCESS_KEY and ALICLOUD_SECRET_KEY per this guide https://help.aliyun.com/knowledge_detail/38738.html` to be the format as below.

Get ALICLOUD_ACCESS_KEY and ALICLOUD_SECRET_KEY per [this guide](https://help.aliyun.com/knowledge_detail/38738.html)

**Comment by barnettZQG** [comment]
正则识别表单帮助字符串中的链接地址，将其展示为a标签。
