### ISSUE TITLE
component webservice UI add env no interaction

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/velaux#289]
![image](https://user-images.githubusercontent.com/2173670/146898308-aadfe036-04e9-4a0e-823f-34d1068b1c8a.png)

**Comment by wangbow** [comment]
![image](https://user-images.githubusercontent.com/21334770/146898878-334307d6-6e5f-4664-8208-d1874e02e05a.png)
现在是点击 图中的实现的

**Comment by wonderflow** [comment]
点 Add 默认要有反应，可以展开右边的选项
