### ISSUE TITLE
Add cache for Logo in web side

### ISSUE THREAD

**Issue by wonderflow** [oam-dev/velaux#290]
![image](https://user-images.githubusercontent.com/2173670/146899704-4dbf4912-d836-4b3b-bb09-7cbe616f9aa3.png)

LOGO 图标前端在浏览器里缓存一下

**Comment by wangbow** [comment]
这个图标不展示的原因是。图标指向的地址不存在，导致图标找不到。。已经推动楚岳来处理ing
![image](https://user-images.githubusercontent.com/21334770/147430731-1e9af2e8-d1de-4823-b00b-833d2aa345d1.png)
