### ISSUE TITLE
Feature: display addon observability as an experimental addon

### ISSUE THREAD

**Issue by zzxwill** [oam-dev/velaux#298]
- [x] Make it work in experimental. Stable to install and uninstall @zzxwill https://github.com/oam-dev/catalog/pull/205
  - [x] https://github.com/oam-dev/kubevela/issues/2992 @chivalryq
- [x] Change the type of Grafana service to `LoadBalancer` and access it by eip. @zzxwill https://github.com/oam-dev/kubevela/pull/2996
- [x] Display the addon in the experimental addon list when velaux is installed https://github.com/oam-dev/kubevela/pull/2993 @wangyikewxgm 
- [x] #299
- [x] An application can display its metrics and logging in Dashboard @barnettZQG #288 @zzxwill https://github.com/oam-dev/velaux/pull/319

**Comment by wangyikewxgm** [comment]
https://github.com/oam-dev/kubevela/pull/2993 In this pr, I have add RegistryName in `/api/v1/addons/` interface such as

```json
    "addons": [
        {
            "name": "fluxcd",
            "version": "1.0.0",
            "description": "Extended workload to do continuous and progressive delivery",
            "icon": "https://raw.githubusercontent.com/fluxcd/flux/master/docs/_files/weave-flux.png",
            "url": "https://fluxcd.io",
            "tags": [
                "extended_workload",
                "gitops"
            ],
            "deployTo": {
                "runtime_cluster": true,
                "disableControlPlane": false,
                "runtimeCluster": false
            },
            "needNamespace": [
                "flux-system"
            ],
            "invisible": false,
            "registryName": "KubeVela"
        },
```

**Comment by zzxwill** [comment]
Observability addon is not core.
![image](https://user-images.githubusercontent.com/2805315/147525938-72c41c56-1217-4804-af92-624f1ebc3663.png)

**Comment by zzxwill** [comment]
Thank you, all.
