### ISSUE TITLE
[BUG] Can't create a Namespace that "shows" doesn't exist in the current  Cluster

### ISSUE THREAD

**Issue by BinaryHB0916** [oam-dev/velaux#308]
https://user-images.githubusercontent.com/57997154/147636730-02b5ff18-2174-4216-910d-56439a2697df.mov

![21656AB1-4081-4958-ABAD-EC88DECC3638](https://user-images.githubusercontent.com/57997154/147637348-3595b0c5-baed-4d4e-9e79-224c4c8657f7.png)

As video and screenshot showed, `prod` namespace doesn't exist in the cluster of ACK-杭州. When creating it, it turns out green but it can't be found in the drop out list.

Reason? 
Highly believe the Target using namespace of `prod` has been created and removed before. But namespace of `prod` remained in the cluster.
Now the namespaces listed in VelaUX DB differentiated from the namespaces listed in the cluster.

**Comment by wangbow** [comment]
https://user-images.githubusercontent.com/21334770/148199888-cd858853-e825-4569-83eb-1edc5e5550f1.mov

**Comment by wangbow** [comment]
@BinaryHB0916   Could you help to check whether the current behavior has met the expectations
