### ISSUE TITLE
[BUG] The terminated workflow's status is the same as the running workflow

### ISSUE THREAD

**Issue by FogDong** [oam-dev/velaux#318]
![image](https://user-images.githubusercontent.com/15977536/148016948-c8c8ee86-0c3d-4aeb-8d93-4dee9dd19cbf.png)

The terminated workflow's status is the same as the running workflow.

/cc @barnettZQG

**Comment by wangbow** [comment]
进过复现问题，前端是从后端API phase中获取状态来展示的，当application被回收后，phase 的状态没有进行相应的变化，期望应该是stopped（雾雾反馈说她来优化下) 
@barnettZQG
