### ISSUE TITLE
[Feature] Gateway trait should show domain in the list page

### ISSUE THREAD

**Issue by FogDong** [oam-dev/velaux#328]
Right now there is no other information on the trait list page.

![image](https://user-images.githubusercontent.com/15977536/148897435-33f2c2e0-b22a-45c1-89bb-35fda27abeaf.png)

If it's a gateway trait, we should show `domain` in its card.

![image](https://user-images.githubusercontent.com/15977536/148897541-9e8738be-59d8-4392-9149-bfd1d30ca5dc.png)

**Comment by barnettZQG** [comment]
The service endpoints are displayed on the environment page.
