### ISSUE TITLE
[Bug] New Target Bug

### ISSUE THREAD

**Issue by FogDong** [oam-dev/velaux#338]
In `New Target`, click `New` beside `Namespace`:

![image](https://user-images.githubusercontent.com/15977536/150463818-5414b27a-9b43-4fdd-8af7-0e0d1a0106be.png)

The Namespace will be null and `New` become `Submit`:

![image](https://user-images.githubusercontent.com/15977536/150463860-8debed38-17d3-4afb-a12a-ef9062438d14.png)

Click again:

![image](https://user-images.githubusercontent.com/15977536/150463882-751a0f0a-2832-4219-992d-794b510e64df.png)

**Comment by barnettZQG** [comment]
@FogDong You should input the namespace before clicking the submit button.

**Comment by FogDong** [comment]
> @FogDong You should input the namespace before clicking the submit button.

The button is first `New`, then `Submit`, it's confusing.
