### ISSUE TITLE
No env options showed in the "Bind Environments" dropdown list when create a new application

### ISSUE THREAD

**Issue by yunjianzhong** [oam-dev/velaux#339]
There are not any options showed in the "Bind Environments" dropdown list when create a new application, even though I created the new environments in env page. This issue may be correlated with the backend data generated by api server. I couldn't find any configmap data for default env, default project, default target in kubevela namespace. Once I copied the default configmap data from one full new KubeVela instance, the issue is disappeared. 

So the issue may be caused by that the api server couldn't generate the default configmap correctly due to some reasons. 

The UI should work properly even though these default data weren't generated.

**Comment by barnettZQG** [comment]
@yunjianzhong 

```
kubectl get configmap  -n kubevela |grep project
```
Please provide the result of executing the preceding command.

**Comment by yunjianzhong** [comment]
veladatabase-vela-project-11                                            1      24h
veladatabase-vela-project-111                                           1      23h
veladatabase-vela-project-121                                           1      24h
veladatabase-vela-project-12321                                         1      23h
veladatabase-vela-project-default                                       1      6d3h
veladatabase-vela-project-zz                                            1      24h

I created configmap "veladatabase-vela-project-default" manually, and the issue was resolved.

**Comment by barnettZQG** [comment]
@yunjianzhong Yes, the "veladatabase-vela-project-default" is required.
