### ISSUE TITLE
UX prompt box problem

### ISSUE THREAD

**Issue by workman-Lu** [oam-dev/velaux#366]
![2a5cb402c0052b33c50a2f42484a05d](https://user-images.githubusercontent.com/23043492/154628728-96491b87-dc76-469d-9985-95ee1d368e55.png)

The Createcluster function default path returns an error in the windows environment without permission, but velaUX returns it is a successful request

![image](https://user-images.githubusercontent.com/23043492/154628995-c4a266d6-382e-4144-8eee-e62e62f33b87.png)
now，is true

**Comment by workman-Lu** [comment]
the box is alway override exception prompts box

**Comment by barnettZQG** [comment]
@workman-Lu ref: https://github.com/oam-dev/velaux/pull/365
