### ISSUE TITLE
[UI] When hits the button of Advanced Parameters when creating component, everything goes wild

### ISSUE THREAD

**Issue by BinaryHB0916** [oam-dev/velaux#381]
UI becomes random and hard to locate.

Before:
![image](https://user-images.githubusercontent.com/57997154/155690197-bb8da573-751e-4e60-ad39-c276902736af.png)

After:
![image](https://user-images.githubusercontent.com/57997154/155690335-cae2217b-ed7a-48b4-ad46-ef0fe239e851.png)

**Comment by barnettZQG** [comment]
This issue is already fixed in 1.3.
