### ISSUE TITLE
[Design] Multi-tenant and authorization

### ISSUE THREAD

**Issue by barnettZQG** [oam-dev/velaux#387]
# Overview
The VelaUX RBAC authorization design for API and UI is suitable for the end-user.

## RBAC authorization
The RBAC authorization mechanism applies only to the resource type, that is, rules that control resource operations based on roles. For example, the permission `Application.Delete`, which means that all applications can be deleted.

## Data authorization
Data authorization can complement RBAC authorization to achieve multi-lease control and important data protection. For example,  Project is a layer of data authorization. Only a member of a project can obtain a role in the RBAC system. In addition, the application can also be individually granted user permissions. For example, a developer can be assigned the observer role in a project but can be assigned some permissions of developer for an application.

# Business and Authorization

## Multi-tenant
In VelaUX, resources such as Target, Application, Environment, Role and User are managed by multi-tenant isolation. Currently, the business concept of "Project" is adopted. Therefore, the basic project management requirements need to be implemented first:

* Create Project
Users who create project permissions can create projects based on the following fields: name、alias、 targets and project owner. The project owner also assigns the default project manager role.

* List Projects
Query the list of all projects. Search by name and alias should be supported.

* Detail a project
Query basic information and statistics of a project.

* List Projects for the logged-in user
Query the project list according to the logged-in user, It does not require additional permissions.

* Modify basic project information
the following fields: alias、targets and owner can be modified.

* Add project members
When adding a user to a project, you need to select one or more roles to 
assigned this user.

* Delete project members
Deletion of project members means withdrawal of authorization to users, and the project owner cannot delete it.

* Modify project members
Member roles can be modified.

At present, "Setting > Projects "is the first menu entry for project management, and the project belongs to the platform-level resource.

##  Platform level RBAC
Platform-level resource authorization supports independent role management, which is mainly used to assign different administrators.

"Setting > Roles "is the menu entry.

* Default Roles
Admin: Set all permissions.

* Add new role
Users create roles based on the following fields: role name, alias, and permission set.

* Modify role
* Add member for a role
* Delete role
* Modify permission set for a role

## Project level RBAC
Project-level resource authorization supports independent role management.
"Setting > Projects > Detail > Roles " is the menu entry.

* Default Role
manager: Set all permissions for resources under the project.

developer: Set all permissions for application and environment.

* new role
* Modify role
* Modify permission set for a role

# Technical solution

## Data model

* Role
    * name
    * alias
    * project:  Left blank represents system-level roles.
    * permissions
 
* Permission：  Format: resource.action 
   ```
   Project/{xxx}/Application/*.Create
   Project/{xxx}/Application/{xxx}.BindEnv
   Project/{xxx}/Application/{xxx}.Deploy
   Project/{xxx}/Application/{xxx}/Environment/{xxx}.Deploy
   ```
* UserRole
  * userID
  * role

## Authorization
POST  /api/v1/projects/xxx/roles   Create the project level role.
POST  /api/v1/roles   Create the platform-level role.
```
{
  "name": "dev",
  "alias": "开发者",
  // means have full application permission and environment creation permission
  "permissions": ["Application.*", "Environment.Create"],
}
```
```
{
  "name": "manager",
  "alias": "管理员",
  // means have full permissions
  "permissions": ["*.*"],
}
```

POST  /api/v1/roles/manager/users   Bind a user to system roles
```
{
  "user": "wanger"
}
```

POST  /api/v1/projects/xxx/members   Add a member for a project.
```
{
  "user": "wanger",
  "roles": ["dev"]
}
```

GET /api/v1/user-permissions   Get the login user permission list
```
{
  "permissions": ["XX.XX"],
  "projects": {
    "xxx": {
      "permissions": ["XX.XX"],
      "applications": {
         "app1": {
           "permissions": ["XX.XX"],
         }
      }
    }
  }
}
```
GET /api/v1/primissions  Get all permission options.

```
[
  {
    "resource": "Cluster"
    "actions": ["Create"]
    "subResources": [{}]
  }
]
```

##  API Authentication

```
ws.Route(ws.DELETE("/{name}").To(c.deleteApplication).
		Doc("delete one application").
		Metadata(restfulspec.KeyOpenAPITags, tags).
		Filter(c.appCheckFilter).
    
                 // Define the project validation interceptor. The API associated with the project-level resource must be defined
		Filter(checkProject).
                 // Defines permission verification interceptors for platform-level resources and project-level resources related apis
		Filter(checkPermission(["Application.Delete"])).
    
		Param(ws.PathParameter("name", "identifier of the application ").DataType("string")).
		Returns(200, "OK", apis.EmptyResponse{}).
		Returns(400, "Bad Request", bcode.Bcode{}).
		Writes(apis.EmptyResponse{}))
```
* checkUser interceptor

Mount interfaces that require user authentication, obtain user information and store it in context. You can also store the set of permissions you own in the context for subsequent interceptor judgment.

* checkProject interceptor

The API related to Project resources needs to be mounted. The interceptor of Project resource permission verification obtains the Project to be accessed according to the path parameter or application parameter and determines whether the Project is authorized to pass according to the login user permission information.

* checkPermission interceptor
* 
All APIs need to be mounted. You need to determine whether the requested user has the corresponding permission based on the required permission data passed in during the definition. No match means no pass.

## UI Authentication

* react component
```
<CheckPermission permissions=["Application.Create"] ><Buttion .../></CheckPermission>

<CheckPermission permissions=["Application.List"] ><Menu.Item .../></CheckPermission>

<CheckPermission project={xx} application={yy} permissions=["Application.Delete"] ><a .../></CheckPermission>
```
* route

Set the required permission based on the route path. If the permission is not met, go to 403 page.

**Comment by zhulaoliu** [comment]
请问什么时候能上线呢？

**Comment by zxbyoyoyo** [comment]
有个不成熟的想法，这个可以参考下aws iam功能来实现，aws用的PBAC模型来实现的，基于Policy来满足灵活的权限控制

**Comment by barnettZQG** [comment]
@zxbyoyoyo The PBAC model like integration of RBAC and ABAC.
