### ISSUE TITLE
text of URL box is not right, when change addon registry type to be aliyunoss

### ISSUE THREAD

**Issue by StevenLeiZhang** [oam-dev/velaux#391]
procedure：
1. go to velaux webpage
2. goto menu "addon"
3. click button "add registries"
4. set the "type" to be "aliyun oss"
5. the text below "URL" box is still"Only support github repo url（master branch）"

expected:
1. should not be text about "github"

**Comment by barnettZQG** [comment]
This is already fixed in 1.3, thanks!
