### ISSUE TITLE
1.3 VelaUX体验反馈

### ISSUE THREAD

**Issue by chivalryq** [oam-dev/velaux#412]
1. 登陆页面没有双语，默认是中文，不知这是否是错误。
2. addon project是不是应该禁止在project下拉列表中选择？
3. recycle的对话框没有中文

**Comment by chivalryq** [comment]
1st isn't a question.

**Comment by barnettZQG** [comment]
@chivalryq 
关于第二点，项目选项是根据不同用户权限而不同的，管理员应该有这个选项。
第三点指什么？

**Comment by chivalryq** [comment]
2. addon project我理解是一个系统级别的project。用户有权限对这个project进行操作，也应该收口在addon部分。而用户自己的application不应该出现在这个project。
3. deploy之后可以点recycle进行资源回收，这个资源回收的对话框没有中文支持。
@barnettZQG

**Comment by wangbow** [comment]
> 1. 登陆页面没有双语，默认是中文，不知这是否是错误。
> 3. recycle的对话框没有中文
1.会进行双语支持
2.会进行文案支持
