### ISSUE TITLE
"ServiceType" is not rendered with correct value on addon "velaux" detail page

### ISSUE THREAD

**Issue by StevenLeiZhang** [oam-dev/velaux#435]
reproduce procedure:
1. install kubvela v1.3.0
2. enable velaux 
```
vela addon enable velaux  repo=xxxx  serviceType=NodePort
```

3.goto velaux webpage, and menu addons
4.click card "velaux" to view details
"ServiceType" is "ClusterIP"

![image](https://user-images.githubusercontent.com/14890978/162876851-a220cdd2-38f4-475b-949c-5758d1e2769d.png)

expected result:
1."ServiceType" is "NodePort"

**Comment by barnettZQG** [comment]
@StevenLeiZhang This is fixed in 1.3.0, please upgrade to 1.3.0

**Comment by StevenLeiZhang** [comment]
> @StevenLeiZhang This is fixed in 1.3.0, please upgrade to 1.3.0

I am sure my verion is v1.3.0, because I fresh installed my vela.
May be something wrong with frontend, because API responses right value.

**Comment by barnettZQG** [comment]
@StevenLeiZhang I'm sorry, it is fixed in [this commit](https://github.com/oam-dev/velaux/commit/d4d2d802e4c8de1a50a55226ca4ca808f0fec206). but merge after the 1.3.0 release, please wait for 1.3.1.

**Comment by barnettZQG** [comment]
@StevenLeiZhang you can try 1.3.0 release.

**Comment by StevenLeiZhang** [comment]
> @StevenLeiZhang I'm sorry, it is fixed in [this commit](https://github.com/oam-dev/velaux/commit/d4d2d802e4c8de1a50a55226ca4ca808f0fec206). but merge after the 1.3.0 release, please wait for 1.3.1.

Yes. I have verified. It works for v1.3.1. Please close this issue.
