### ISSUE TITLE
[Frontend] Use Protobuf definitions from pkg/proto/model to generate JS APIs

### ISSUE THREAD

**Issue by hongchaodeng** [oam-dev/velaux#93]
Currently these ts APIs are manually written. Need to generate those from pkg/proto/model proto types, and replace `src/services/kubevela/typings.d.ts`

**Comment by wangyuan249** [comment]
###  Progress
After my research, there is currently a success (can-run) version Typescript type  generated from proto file . 
In PR: https://github.com/oam-dev/velacp/pull/117 .
But there are still some problems: 
1. For example, the old file "typing.d.ts" define the clusterType  as a typescript type. and the new cluster_pb.d.ts define the cluster as a typescript class.

In cmd:
```
pbjs -t  static-module -w commonjs -o  cluster_pb.js   cluster.proto
pbts -o  cluster_pb.d.ts  cluster_pb.js
```
In generate file:
```
/** Properties of a Cluster. */
            interface ICluster {

                /** Cluster name */
                name?: (string|null);

                /** Cluster desc */
                desc?: (string|null);

                /** Cluster updatedAt */
                updatedAt?: (number|Long|null);

                /** Cluster kubeconfig */
                kubeconfig?: (string|null);
            }

            /** Represents a Cluster. */
            class Cluster implements ICluster {

                /**
                 * Constructs a new Cluster.
                 * @param [properties??] Properties to set
                 */
                constructor(properties?: vela.api.model.ICluster);

                /** Cluster name. */
                public name: string;

                /** Cluster desc. */
                public desc: string;

                /** Cluster updatedAt. */
                public updatedAt: (number|Long);

                /** Cluster kubeconfig. */
                public kubeconfig: string;
                ...
                ...
                ...
                /**
                 * Converts this Cluster to JSON.
                 * @returns JSON object
                 */
                public toJSON(): { [k: string]: any };

```
Therefore, when we Call cluster variables in other functions, we should rewrite the toJSON() function.
![image](https://user-images.githubusercontent.com/35907099/122009119-58c1bd80-cdec-11eb-915f-ca2de4e298ab.png)
And this makes our type references more complicated. Thus, current version commented out the toJSON method of the original generated class.

Looking for a better solution for replacement or we should re-design the "type reference"  in frontend.

2. The above work is to generate JS Types.  As for generating JS APIs,  Current proto file still lack of service definition like 
```
service SearchService {
  rpc Search (SearchRequest) returns (SearchResponse);

}
```
And we  need to plan and align the service interface of the frontend and backend.
